const channels = [
  {

    id:"w6d0j",
    name: "wanderlust diaries",
    subscribers:1558,
    noofvideos: 23,
    totalviews: 39751,
  },
  {
    id:"ty82e",
    name: "culinary delights",
    subscribers:1399,
    noofvideos: 8,
    totalviews: 10226,
  },
  {
    id:"tg6ge",
    name: "mindful moments",
    subscribers:866,
    noofvideos: 37,
    totalviews: 13311,
  },
  {
    id:"h1vxo",
    name: "funny animals",
    subscribers:1177,
    noofvideos: 29,
    totalviews: 47992,
  },
  {
    id:"cs4gd",
    name: "tech savvy",
    subscribers:1400,
    noofvideos: 21,
    totalviews: 8324,
  },
  {
    id:"syy3v",
    name: "nature wonders",
    subscribers:1943,
    noofvideos: 37,
    totalviews: 46276,
  },
  {
    id:"jphds",
    name: "green earth",
    subscribers:1832,
    noofvideos: 4,
    totalviews: 30736,
  },
  {
    id:"t6llv",
    name: "creative spaces",
    subscribers:1387,
    noofvideos: 47,
    totalviews: 14859,
  },
  {
    id:"gzl4o",
    name: "adventure sports",
    subscribers:1293,
    noofvideos: 16,
    totalviews: 37675,
  },
  {
    id:"ciwoy",
    name: "gourmet kitchen",
    subscribers:1977,
    noofvideos: 1,
    totalviews: 45699,
  },
  {
    id:"nfncc",
    name: "movie buff",
    subscribers:1296,
    noofvideos: 24,
    totalviews: 42693,
  },
  {
    id:"9lyf2",
    name: "language lab",
    subscribers:1453,
    noofvideos: 22,
    totalviews: 7779,
  },
  {
    id:"6sogo",
    name: "style central",
    subscribers:1181,
    noofvideos: 45,
    totalviews: 39065,
  },
  {
    id:"orxmn",
    name: "science simplified",
    subscribers:1191,
    noofvideos: 17,
    totalviews: 31412,
  },
  {
    id:"hk4hn",
    name: "peaceful melodies",
    subscribers:1726,
    noofvideos: 47,
    totalviews: 24472,
  },
  {
    id:"zpcb3",
    name: "gadget guru",
    subscribers:1604,
    noofvideos: 15,
    totalviews: 35026,
  },
  {
    id:"pyzje",
    name: "history hub",
    subscribers:1497,
    noofvideos: 50,
    totalviews: 3029,
  },
  {
    id:"2xyoz",
    name: "shutterbug",
    subscribers:1165,
    noofvideos: 40,
    totalviews: 44258,
  },
  {
    id:"gmb2p",
    name: "laugh out loud",
    subscribers:1899,
    noofvideos: 1,
    totalviews: 18591,
  },
];

export default channels;
